version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=kaiodev
      - POSTGRESQL_PASSWORD=docker123
      - POSTGRESQL_DATABASE=database_development

